require 'active_record/remote'

require 'rlm_logistics/client'
require 'rlm_logistics/record/address'
require 'rlm_logistics/record/credit'
require 'rlm_logistics/record/inventory'
require 'rlm_logistics/record/item'
require 'rlm_logistics/record/line'
require 'rlm_logistics/record/packed_order'
require 'rlm_logistics/record/sales_order'